{
    "name": "AOS ROI Generator",
    "summary": "Generate 60-month ROI sheet for alignments/returns",
    "version": "1.0.0",
    "author": "AutoGenerated",
    "category": "Tools",
    "depends": ["base"],
    "data": [
        "security/ir.model.access.csv",
        "views/aos_roi_views.xml"
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}

