{
    'name': 'Odoo WhatsApp Integration | Odoo Meta WhatsApp Graph API | Odoo V19 Community Edition',
    'version': '1.0',
    'author': 'TechUltra Solutions Private Limited',
    'category': 'Base',
    'live_test_url': 'https://www.techultrasolutions.com/blog/news-2/odoo-whatsapp-integration-a-boon-for-business-communication-25',
    'website': 'www.techultrasolutions.com',
    'price': 99,
    'currency': 'USD',

    'depends': ['base', 'mail', 'mail_group', 'base_automation','aos_vehicle_aretx'],
    'data': [
        'security/whatsapp_security.xml',
        'security/ir.model.access.csv',
        'data/cron.xml',
        'data/wa_template.xml',
        'wizard/wa_compose_message_view.xml',
        'views/res_config_settings_views.xml',
        'views/provider_base.xml',
        'views/res_users.xml',
        'views/channel_provider_line.xml',
        'views/res_partner.xml',
        'views/wa_cron_log_views.xml',
        'views/whatsapp_history.xml',
        'views/wa_template.xml',
        'views/variables.xml',
        'views/components.xml',
        'views/mail_channel.xml',
        'views/mail_message.xml',
        'views/provider_meta.xml',
        'views/ir_actions.xml',
        'views/interactive_list_views.xml',
        'views/interactive_product_list_views.xml',
        'views/wa_button_component_views.xml',
        'views/wa_carousel_component_view.xml',
    ],
    'assets': {
        'web.assets_backend': [
            '/aos_whatsapp_base_aretx/static/src/scss/kanban_view.scss',
            '/aos_whatsapp_base_aretx/static/src/css/style.css',
        ],
    },
    'external_dependencies': {
        'python': ['phonenumbers'],
    },
    'installable': True,
    'auto_install': False,
    'license': 'OPL-1',
    'images': ['static/description/tus_banner.gif'],
}
